repos:
  -   repo: https://github.com/psf/black

    # You can pin to a specific version of black
    rev: stable

    hooks:
      -   id: black
          language_version: python3.6
          args: [--safe, --quiet]